server:
  port: 8080

PINECONE_API_KEY: pcsk_6Tysj1_SPB3CBM5RY5gSci1xvVSJuNUtKP7ZnT99Ce9DjG5aKKap1yxALksPBxBQfJd4pC

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: sk-321bce68acd3439985428b6202f8f766
      model-name: deepseek-v3
      #      api-key: sk-rhpWsFiunpG1oKjy3a8e55760477442b8f0688Db9b0715C2
      #      model-name: gpt-3.5-turbo
      log-requests: true
      log-responses: true
  #      base-url: https://api.xty.app/v1/
  ollama:
    chat-model:
      base-url: http://localhost:11434
      model-name: deepseek-r1:1.5b
      log-requests: true
      log-responses: true
      timeout: PT60S
      temperature: 0.8
  community:
    dashscope:
      chat-model:
        api-key: sk-321bce68acd3439985428b6202f8f766
        model-name: qwen-max
      #集成阿里通义千问-通用文本向量-v3
      embedding-model:
        api-key: sk-321bce68acd3439985428b6202f8f766
        model-name: text-embedding-v3
      #集成阿里通义千问-流式输出
      streaming-chat-model:
        api-key: sk-321bce68acd3439985428b6202f8f766
        model-name: qwen-plus
# mongoDB连接配置
spring:
  data:
    mongodb:
      host: 101.42.154.219
      port: 27017
      database: chat_memory_db
      authentication-database: admin
#      username: mongo
#      password: mongo
  # MySQL配置
  datasource:
    url: jdbc:mysql://101.42.154.219:3306/meta_study?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
# MyBatis配置
mybatis:
  configuration:
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

logging:
  level:
    root: debug
